### ISSUE TITLE
ModuleNotFoundError: No module named 'ldm.models'

### ISSUE THREAD

**Issue by milely** [ali-vilab/Ranni#1] opened 2024-04-08 12:12 UTC
Thank you for work. 
The error encountered during runtime is as follows.
![image](https://github.com/ali-vilab/Ranni/assets/19663249/00785c11-5963-4a48-9d5c-e36402e224a3) 
It seems that the models is missed in ldm package

**Comment by DuoLi1999** [comment] 2024-04-08 12:13
same issue

**Comment by DuoLi1999** [comment] 2024-04-08 13:15
> Thank you for work. The error encountered during runtime is as follows. ![image](https://private-user-images.githubusercontent.com/19663249/320476861-00785c11-5963-4a48-9d5c-e36402e224a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODIwNzksIm5iZiI6MTcxMjU4MTc3OSwicGF0aCI6Ii8xOTY2MzI0OS8zMjA0NzY4NjEtMDA3ODVjMTEtNTk2My00YTQ4LTlkNWMtZTM2NDAyZTIyNGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEzMDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMWE0YWQ5MDI5ZTk4ZWQ2MTE1ZDllZDUwZmQ5MWEyZjZiMjNlYzgxMWUyYTAzMzdkNjJlNmVjMmQzMTQ0ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xtflqy7o6jaHYN2xwXsfgiHkHXsFMSg5ll8eEtodkvA) It seems that the models is missed in ldm package

I've fixed this issue. You can use the ldm.model available at this [link](https://github.com/Stability-AI/stablediffusion/tree/main/ldm/models). Pay attention to the version compatibility of pytorch-lightning and gradio.

**Comment by thss15fyt** [comment] 2024-04-08 13:28
Thanks for your interest.
This is a bug caused by wrong .gitignore. Fixed now.

**Closed** 2024-04-09 01:45 UTC
